In [109]:
import pandas as pd
import numpy as np
from sklearn.metrics import *
path_to_insults = '/Users/dattasainathd/Downloads/'
data2 = pd.read_csv(path_to_insults + 'final_train_bot.csv',na_values='0', encoding = "ISO-8859-1", nrows = 1320)
data2['no'] = 0
for x in range(0,data2.shape[0]):
    data2.loc[x, 'no']=x 
data2['Value'] = 1
data2['bot'] = 1
data2 = data2.drop('created_at', axis=1)
data2.verified=data2.verified.astype(int)
data2.default_profile=data2.default_profile.astype(int)
data2.default_profile_image=data2.default_profile_image.astype(int)
data2 = data2.drop('status', axis=1)
data2 = data2.drop('id', axis=1)
data2 = data2.drop('id_str', axis=1)
data2 = data2.drop('url', axis=1)
data2 = data2.drop('has_extended_profile', axis=1)
data2.location.fillna('', inplace=True)
data2.description.fillna('', inplace=True)
data2.followers_count.fillna(0, inplace=True)
data2.friends_count.fillna(0, inplace=True)
data2.listedcount.fillna(0, inplace=True)
data2.statuses_count.fillna(0, inplace=True)
data2.favourites_count.fillna(0, inplace=True)
data2.followers_count=data2.followers_count.astype(int)
data_description = data2['description'].str.lower()
data_name = data2['name'].str.lower()
data_screen_name = data2['screen_name'].str.lower()
bot = 'bot'
count = 0
serial = -1
for x in data_screen_name:
    serial = serial + 1
    if bot in x:
        data2.ix[serial, 'Value'] = 2
        count += 1
serial = -1
count2 = 0
for x in data_name:
    serial = serial + 1
    try:
        if bot in x:
            data2.ix[serial, 'Value'] = 2
            count2 += 1
    except:
        pass
serial = -1
count3 = 0
for x in data_description:
    serial = serial + 1
    try:
        if bot in x:
            data2.ix[serial, 'Value'] = 2
            count3 += 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==1):
            if(data2.loc[serial, 'statuses_count']==0 or data2.loc[serial, 'followers_count']==0 or 
               data2.loc[serial, 'friends_count']==0 ):
                data2.loc[serial, 'Value'] = 3
                count+=1
                
            
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==1):
            if((data2.loc[serial, 'statuses_count']/data2.loc[serial, 'followers_count']<12 
                and data2.loc[serial, 'statuses_count']/data2.loc[serial, 'friends_count']<12)):
                data2.loc[serial, 'Value'] = 3
                count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'verified']==1):
            data2.loc[serial, 'Value'] = 3
            count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==1 or data.loc[serial, 'Value']==2):
            if((data2.loc[serial, 'statuses_count']/data2.loc[serial, 'followers_count']>10 
                or data2.loc[serial, 'statuses_count']/data2.loc[serial, 'friends_count']>10)):
                data2.loc[serial, 'Value'] = 2
                count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==3):
            data2.loc[serial, 'Value'] = 0
        else:
            data2.loc[serial, 'Value'] = 1
        count+= 1
    except:
        pass
data_value = data2['Value']
datafinal = data2['bot']
print("Accuracy Score: ", (accuracy_score(datafinal, data_value)))
cnf_matrix = confusion_matrix(datafinal, data_value)
print("Confusion Matrix:")
print(cnf_matrix)

/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:106: RuntimeWarning: divide by zero encountered in double_scalars
/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:105: RuntimeWarning: invalid value encountered in double_scalars
/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:105: RuntimeWarning: divide by zero encountered in double_scalars
/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:106: RuntimeWarning: invalid value encountered in double_scalars

Accuracy Score:  0.745454545455
Confusion Matrix:
[[  0   0]
 [336 984]]

In [110]:
data3 = data2[data2.Value != 0]
data3.head(2)
data3 = data3.drop('Value', axis=1)
data3 = data3.drop('no', axis=1)

In [111]:
data3.shape

(984, 14)

In [112]:
import pandas as pd
import numpy as np
from sklearn.metrics import *
path_to_insults = '/Users/dattasainathd/Downloads/'
data2 = pd.read_csv(path_to_insults + 'final_train_nonbot.csv',na_values='0', encoding = "ISO-8859-1", nrows = 1477)

data2['no'] = 0
for x in range(0,data2.shape[0]):
    data2.loc[x, 'no']=x
print("Made a serial column which can be used for plotting purposes")  

print("Initializing two rows of Value with 0 & user with 1")
data2['Value'] = 0
data2['user'] = 1

data2 = data2.drop('created_at', axis=1)
data2.verified=data2.verified.astype(int)
data2.default_profile=data2.default_profile.astype(int)
data2.default_profile_image=data2.default_profile_image.astype(int)

data2 = data2.drop('status', axis=1)
data2 = data2.drop('id', axis=1)
data2 = data2.drop('id_str', axis=1)
data2 = data2.drop('url', axis=1)
data2 = data2.drop('has_extended_profile', axis=1)

data2.location.fillna('', inplace=True)
data2.description.fillna('', inplace=True)
data2.followers_count.fillna(0, inplace=True)
data2.friends_count.fillna(0, inplace=True)
data2.listedcount.fillna(0, inplace=True)
data2.statuses_count.fillna(0, inplace=True)
data2.favourites_count.fillna(0, inplace=True)
data2.followers_count=data2.followers_count.astype(int)
data_description = data2['description'].str.lower()
data_name = data2['name'].str.lower()
data_screen_name = data2['screen_name'].str.lower()
bot = 'bot'

print("Checking for the 'bot' word in the screen names of the accounts")
count = 0
serial = -1
for x in data_screen_name:
    serial = serial + 1
    if bot in x:
        data2.ix[serial, 'Value'] = 2
        count += 1
serial = -1

print("No.of accounts which had 'bot' in screen name: ", count)
print("accuracy", count/data2.shape[0])

print("Checking for the 'bot' word in the names of the accounts")
count2 = 0
for x in data_name:
    serial = serial + 1
    try:
        if bot in x:
            data2.ix[serial, 'Value'] = 2
            count2 += 1
    except:
        pass
print("No.of accounts which had 'bot' in names: ", count2)
print("accuracy", count2/data2.shape[0])
serial = -1
print("Checking for the 'bot' word in the description of the accounts")
count3 = 0
for x in data_description:
    serial = serial + 1
    try:
        if bot in x:
            data2.ix[serial, 'Value'] = 2
            count3 += 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==0):
            if(data2.loc[serial, 'statuses_count']==0 or data2.loc[serial, 'followers_count']==0 or 
               data2.loc[serial, 'friends_count']==0 ):
                data2.loc[serial, 'Value'] = 3
                count+=1
                
            
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==0):
            if((data2.loc[serial, 'statuses_count']/data2.loc[serial, 'followers_count']<12 
                or data2.loc[serial, 'statuses_count']/data2.loc[serial, 'friends_count']<12)):
                data2.loc[serial, 'Value'] = 3
                count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'verified']==1):
            data2.loc[serial, 'Value'] = 3
            count+= 1
    except:
        pass
print("trying to filter accounts which are verified all the verified user accounts are humans")
print("twitter user accounts which are verified are assigned to value 3")
print("total no. of verified users:", count)
print("accuracy", count/data2.shape[0])
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==1 or data.loc[serial, 'Value']==0):
            if((data2.loc[serial, 'statuses_count']/data2.loc[serial, 'followers_count']>10 
                or data2.loc[serial, 'statuses_count']/data2.loc[serial, 'friends_count']>10)):
                data2.loc[serial, 'Value'] = 2
                count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==2):
            data2.loc[serial, 'Value'] = 0
        else:
            data2.loc[serial, 'Value'] = 1
        count+= 1
    except:
        pass
data_value = data2['Value']
datafinal = data2['user']
print("Accuracy Score: ", (accuracy_score(datafinal, data_value)))
cnf_matrix = confusion_matrix(datafinal, data_value)
print("Confusion Matrix:")
print(cnf_matrix)

Made a serial column which can be used for plotting purposes
Initializing two rows of Value with 0 & user with 1
Checking for the 'bot' word in the screen names of the accounts
No.of accounts which had 'bot' in screen name:  10
accuracy 0.006775067750677507
Checking for the 'bot' word in the names of the accounts
No.of accounts which had 'bot' in names:  7
accuracy 0.0047425474254742545
Checking for the 'bot' word in the description of the accounts
trying to filter accounts which are verified all the verified user accounts are humans
twitter user accounts which are verified are assigned to value 3
total no. of verified users: 645
accuracy 0.4369918699186992

/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:127: RuntimeWarning: divide by zero encountered in double_scalars

Accuracy Score:  0.575880758808
Confusion Matrix:
[[  0   0]
 [626 850]]

/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:126: RuntimeWarning: divide by zero encountered in double_scalars

In [113]:
data2 = data2.drop('Value', axis=1)
data2 = data2.drop('no', axis=1)
data2 = data2.drop('user', axis=1)
data2['bot'] = 0

In [114]:
data2.shape

(1476, 14)

In [115]:
result = pd.concat([data3, data2], ignore_index=True)

In [116]:
result

,screen_name,location,description,followers_count,friends_count,listedcount,favourites_count,verified,statuses_count,lang,default_profile,default_profile_image,name,bot
0,"""HoustonPokeMap""","""Houston, TX""","""Rare and strong PokÅ½mon in Houston, TX. See ...",1291,0.0,10.0,0.0,0,78554.0,"""en""",1,0,"""Houston PokÅ½ Alert""",1
1,kernyeahx,"Templeville town, MD, USA",From late 2014 Socium Marketplace will make sh...,1,349.0,0.0,38.0,0,31.0,en,1,0,Keri Nelson,1
2,mattlieberisbot,,"Inspired by the smart, funny folks at @replyal...",1086,0.0,14.0,0.0,0,713.0,en,1,0,Matt Lieber Is Bot,1
3,lucarivera16,"Dublin, United States",Inspiring cooks everywhere since 1956.,11,745.0,0.0,146.0,0,185.0,en,0,0,lucarivera16,1
4,dantheimprover,"Austin, TX",Just a guy trying to do good by telling everyo...,1,186.0,0.0,0.0,0,11.0,en,1,0,dantheimprover,1
5,_all_of_us_,in a machine.,bot by @rubicon,193,0.0,19.0,0.0,0,6068.0,en,0,0,everything always,1
6,KatamariItems,,[Bot rolled up by @BeachEpisode] Cataloguing e...,8227,2.0,89.0,26.0,0,2597.0,en,1,0,Katamari Collection,1
7,AutophagyPapers,,Twitterbot for #Autophagy papers. Curated by @...,275,0.0,17.0,23.0,0,9922.0,en,0,0,Autophagy Papers,1
8,HSC_papers,,,51,3.0,9.0,0.0,0,2515.0,en,1,0,Hematopoiesis,1
9,everycheese,cheese land,cheese cheese cheese // updates every 4 hours ...,51,1.0,12.0,0.0,0,111.0,en,0,0,all of the cheese,1
10,gyr_papers,,"Literature bot searching arXiv, biorXiv, PeerJ...",2,1.0,4.0,0.0,0,230.0,en,1,1,gyrpapers,1
11,hard_to_yelp,,,109,0.0,16.0,0.0,0,16067.0,en,1,0,how hard is it to,1
12,fuckeverywordza,,Why wait until 2020 for the Z's? Fucking every...,250,0.0,25.0,0.0,0,31721.0,en,1,0,fuck every word z-a,1
13,yeahTonyaGonzal,"Pensacola, USA","Musician, vegan, animal rights activist.",15,1941.0,1.0,319.0,0,406.0,en,0,0,yeahTonyaGonzal,1
14,ecin_gnihtaseod,,"straight-up rip-off of @doesathing_nice, excep...",181,0.0,24.0,0.0,0,21506.0,en,1,1,âÂÆÃâ¡Â«Ã¤u,1
15,onetruewiseman,AMERICA,The Truest Wisdom (aka trying to make even les...,23,4.0,8.0,4.0,0,6230.0,en,0,0,One True Wise Man,1
16,everycolorbot,the RGB color space,colors. all of 'em. | developed by @vogon; fe...,106126,0.0,999.0,2.0,0,30156.0,en,1,0,Every Color,1
17,himawari8bot,Space,Unofficial; imagery courtesy: Japan Meteorolog...,2302,3.0,161.0,4.0,0,7640.0,en,0,0,himawari8bot,1
18,emoji__polls,â°Ã·Ââ¢Ã¼Â,A silly bot by @fourtonfish @botwikidotorg. Im...,443,2.0,17.0,6.0,0,9584.0,en,0,0,EMOJI POLLS!,1
19,everytrolltroll,,exposing the BLATANT HYPOCRISY of @everycanont...,27,1.0,10.0,0.0,0,145.0,en,1,0,EveryCanonTrollTroll,1
20,hyphizer,#botALLY,"New words, from time to time. By @derekarnold",191,2.0,19.0,0.0,0,5684.0,en,0,0,hyphizer,1
21,GreenwadeGema,,secr,1,35.0,1.0,54.0,0,82.0,en,1,0,Gema Greenwade,1
22,par_papers,,"Twitterbot of #Parasitology papers in PubMed, ...",651,0.0,36.0,0.0,0,19867.0,en,0,0,Parasitology papers,1
23,assembly_papers,,Papers on directed and self assembly,331,56.0,36.0,23.0,0,29989.0,en,1,0,assemblypapers,1
24,DeepDreamThis,"London, England",Tweet me a picture and I'll #deepdream it for ...,1327,2.0,92.0,0.0,0,24199.0,en,1,0,Deep Dream This,1
25,dstroyeveryword,,Destroy every word in the english language. Ta...,4247,2.0,72.0,587.0,0,109325.0,en,0,0,destroy every word,1
26,snowcloneminute,,A mashup of http://t.co/Tdj0YYLDOM and http://...,163,2.0,74.0,64.0,0,552492.0,en,1,0,Snowclone-a-Minute,1
27,NESGarbageBot,,Tweets randomly-generated 16x16 images using t...,32,1.0,12.0,0.0,0,6181.0,en,1,0,NES Garbage Bot,1
28,BklynMuseumBot,"Brooklyn, NY",I am a bot that tweets one random object from ...,903,1.0,50.0,0.0,0,3654.0,en,0,0,Brooklyn Museum Bot,1
29,clitoscope,,A compendium of newly discovered species of cl...,108,10.0,9.0,10.0,0,537.0,en,0,0,Clitoris Vulgaris,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2430,cesarmillan,"Los Angeles, CA",I rehabilitate dogs. I train people. I hope th...,1017758,6985.0,9473.0,12901.0,1,13786.0,en,0,0,Cesar Millan,0
2431,mayauofa213,"Tucson, AZ",,9,97.0,0.0,0.0,0,1.0,en,1,0,Carlos Maya,0
2432,Andy,"íìT: 40.735225,-74.006791","folo: @bravowwhl, Insta: @bravoandy, Snap: And...",2000567,457.0,9674.0,901.0,1,55202.0,en,0,0,Andy Cohen,0
2433,"""VicenteTao""","""""","""""",11,53.0,0.0,1.0,0,13.0,"""en""",1,0,"""Tang Tao""",0
2434,kar2905,"Santa Monica, California","Founder @springroleinc, Masters grad from Carn...",1599,922.0,67.0,212.0,0,11240.0,en,0,0,Kartik Mandaville,0
2435,palalablo,,"If I could stay in the shower all day, I would.",82,91.0,0.0,634.0,0,704.0,es,0,0,Pablo,0
2436,dutt_ashish,"Bangalore, India","I'm Ashish Dutt, a Freelance Writer and Photog...",178,325.0,6.0,30.0,0,405.0,en,0,0,Ashish Dutt,0
2437,KellerSeason,,,46,233.0,0.0,935.0,0,285.0,en,1,0,season keller,0
2438,VitorBecker,Santos,,67,168.0,0.0,0.0,0,1851.0,en,0,0,Vitor Vaqueiro,0
2439,honorsociety,"Los Angeles, CA",https://t.co/qnAibV0nJv,147441,20889.0,0.0,43.0,1,7648.0,en,0,0,Honor Society,0
2440,brian_littrell,Some where over the rainbow :),Husband / Father/ Backstreet Boy / Christian A...,420699,108.0,5248.0,11.0,1,5568.0,en,0,0,Brian Littrell,0
2441,TomJackson57,,"Husband, Father, Bronco, ESPN NFL MNF Correspo...",63866,21.0,2037.0,40.0,1,70.0,en,0,0,Tom Jackson,0
2442,visu_bio,www.mnrindia.org,MNRF for Research n Innovation @ClubSciWri Alu...,1715,1342.0,84.0,3688.0,0,1395.0,en,0,0,Viswanadham Duppatla,0
2443,VivianePatty,Brasil/Rio de Janeiro,Estou a procura de amizades sinceras e bem leg...,5,67.0,0.0,0.0,0,2.0,pt,0,0,Viviane Patty,0
2444,mohsin_shk11,"Mumbai, India","Loves sports, movies and reading. Social media...",122,88.0,0.0,325.0,0,1031.0,en,0,0,Mohsin Shaikh,0
2445,Robbie_OC,,For Booking and Contact Eileen Koch & Company ...,4025,487.0,117.0,18.0,1,6672.0,en,0,0,Lewis Rocc,0
2446,MiThiicSource,Canada,13 // Co-Owner Of DSYR // @YouTube Content Cre...,52,39.0,0.0,689.0,0,206.0,en,0,0,mithiicsource,0
2447,"""JTJ_Photo""","""Washington, DC Metro Area""","""Photographer specializing in garden and lands...",30,72.0,4.0,1.0,0,926.0,"""en""",0,0,"""Josh Taylor""",0
2448,SkillzVa,Worldwide,DJ/Host/Artist/Grammy Nominated Songwriter/Mus...,41776,1158.0,854.0,1264.0,1,1096.0,en,0,0,Mad Skillz,0
2449,iamadityar,"New York, NY","Indian, Student of Science",52,323.0,2.0,696.0,0,767.0,en,0,0,Aditya Ramamurthy,0
2450,haileybaldwin,East Coast,Hailey Rhode Baldwin instagram¢haileybaldwin...,972032,3072.0,1587.0,1423.0,1,22362.0,en,0,0,Hailey Baldwin,0
2451,ahmadriaz,,,26,150.0,1.0,8.0,0,2.0,en,1,1,Ahmad Riaz,0
2452,thetrickisto,"Brooklyn, NY","Tell me your successes, I want to steal them. ...",215,462.0,16.0,812.0,0,2384.0,en,0,0,Rose Bender,0
2453,OKKenna,info@kenna.com,,64219,667.0,698.0,2901.0,1,85.0,en,0,0,Kenna,0
2454,MixologyBot,,Feeling adventurous? Try one of these!,310,0.0,21.0,3.0,0,3909.0,en,1,0,The Mixologist,0
2455,leslieberland,,"Twitter CMO. Favorite title: Mama. Never, ever...",18998,2005.0,425.0,2503.0,0,3498.0,en,0,0,Leslie Berland,0
2456,SamuelsPants,brooklyn NY,"I live in brooklyn, I'm a bike messenger, I pl...",32,54.0,0.0,1.0,0,97.0,en,1,0,Samuel Littlefield,0
2457,jimmyfallon,"New York, New York",astrophysicist,45044433,7451.0,68157.0,24.0,1,9606.0,en,0,0,jimmy fallon,0
2458,LocalAlligator,"England, United Kingdom","I'm quite out of my mind, actually, but people...",16,64.0,1.0,15.0,0,62.0,en,0,0,Tammas Foxdene,0
2459,RepJoeBarton,"Ennis, TX",I work for the people of the 6th District of T...,22490,308.0,1342.0,43.0,1,1897.0,en,1,0,Joe Barton,0

In [117]:
#NOW THE TRAINING ACCURACY BEGINS
data = result
data['Value'] = 0
data_description = data['description'].str.lower()
data_name = data['name'].str.lower()
data_screen_name = data['screen_name'].str.lower()
bot = 'bot'
serial = -1

for x in data_screen_name:
    serial = serial + 1
    if bot in x:
        data.ix[serial, 'Value'] = 1
        
serial = -1

for x in data_name:
    serial = serial + 1
    try:
        if bot in x:
            data.ix[serial, 'Value'] = 1
    except:
        pass

serial = -1

for x in data_description:
    serial = serial + 1
    try:
        if bot in x:
            data.ix[serial, 'Value'] = 1
    except:
        pass

In [118]:
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==0):
            if(data.loc[serial, 'statuses_count']==0 or data.loc[serial, 'followers_count']==0 or 
               data.loc[serial, 'friends_count']==0 ):
                data.loc[serial, 'Value'] = 2
                count+=1
    except:
        pass
count

154

In [119]:
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==0):
            if((data.loc[serial, 'statuses_count']/data.loc[serial, 'followers_count']<12 
                and data.loc[serial, 'statuses_count']/data.loc[serial, 'friends_count']<12)):
                data.loc[serial, 'Value'] = 2
                count+= 1
    except:
        pass
count

902

In [120]:
#trying to filter accounts which are verified all the verified user accounts are humans
#because twitter verifies users only 
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'verified']==1):
            data.loc[serial, 'Value'] = 2
            count+= 1
    except:
        pass
count

647

In [121]:
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==0):
            if((data.loc[serial, 'statuses_count']/data.loc[serial, 'followers_count']>10 
                or data.loc[serial, 'statuses_count']/data.loc[serial, 'friends_count']>10)):
                data.loc[serial, 'Value'] = 1
                count+= 1
    except:
        pass
count

571

In [122]:
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']!=1):
            data.loc[serial, 'Value'] = 0
            count+= 1
    except:
        pass
count

1378

In [123]:
data_value = data['Value']
datafinal = data['bot']


print("Accuracy Score: ", (accuracy_score(datafinal, data_value)))
cnf_matrix = confusion_matrix(datafinal, data_value)
print("Confusion Matrix:")
print(cnf_matrix)

Accuracy Score:  0.847154471545
Confusion Matrix:
[[1239  237]
 [ 139  845]]

In [132]:
print("Precision Score: ", (precision_score(datafinal, data_value)))
print("Recall Score: ", (recall_score(datafinal, data_value)))
print("f1 Score: ", (f1_score(datafinal, data_value)))
print("ROC AUC Score: ", (roc_auc_score(datafinal, data_value)))
print("Mean Squared Error: ", (mean_squared_error(datafinal, data_value)))

Precision Score:  0.780961182994
Recall Score:  0.858739837398
f1 Score:  0.818005808325
ROC AUC Score:  0.849085365854
Mean Squared Error:  0.152845528455

In [135]:
fpr, tpr, thresholds = roc_curve(datafinal, data_value)

In [136]:
fpr

array([ 0.        ,  0.16056911,  1.        ])

In [137]:
tpr

array([ 0.        ,  0.85873984,  1.        ])

In [ ]:
neg_mean_squared_error